# Generated by Django 2.0.8 on 2018-08-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('full_name', models.CharField(blank=True, max_length=110, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer', to_field='full_name'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'last_name')},
        ),
    ]
