# Generated by Django 2.0.8 on 2018-08-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180812_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Customer', to_field='full_name'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
